name: verification

on:
  push:
  pull_request:

jobs:
  host:
    runs-on: ubuntu-latest
    env:
      OMP_NUM_THREADS: 4
      RTL_VERIFICATION_REQUIRED: 1
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install host dependencies
        run: sudo apt-get update -qq && sudo apt-get install -y libjudy-dev verilator
      - name: Repository verification
        run: make verify
